### ISSUE TITLE
[error] - csn history

### ISSUE THREAD

**Issue by polo002** [ChestShop-authors/ChestShopNotifier#35]
Occurs when viewing the history:

[00:45:35 WARN]: [ChestShopNotifier] Plugin ChestShopNotifier v1.2.1-SNAPSHOT (build #23) generated an exception while executing task 635
java.lang.IllegalStateException: CurrencyFormatEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-226]
at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:455) ~[?:?]
at com.Acrobot.ChestShop.Economy.Economy.formatBalance(Economy.java:71) ~[?:?]
at com.Acrobot.ChestShop.Economy.Economy.formatBalance(Economy.java:81) ~[?:?]
at com.wfector.command.History.showResults(History.java:130) ~[?:?]
at com.wfector.command.History.run(History.java:46) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-226]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-226]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]

**Comment by Phoenix616** [comment]
You are running an outdated version, this issue is already fixed. Please update to the latest build.
