### ISSUE TITLE
Errors after updating from Build 41 to 44.

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShopNotifier#45]
Recently updated ChestShop from 270 to 273 and ChestShopNotifier from 41 to 44.
Getting the following on server startup:

```
[12:15:57] [Craft Scheduler Thread - 8/INFO]: [com.wfector.lib.hikari.HikariDataSource] HikariPool-1 - Starting...
[12:15:57] [Craft Scheduler Thread - 8/INFO]: [com.wfector.lib.hikari.HikariDataSource] HikariPool-1 - Start completed.
[12:15:57] [Craft Scheduler Thread - 8/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'CustomerName'
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:386)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2585)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1464)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.wfector.lib.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.wfector.lib.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.wfector.notifier.ChestShopNotifier$2.run(ChestShopNotifier.java:149)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[12:15:57] [Craft Scheduler Thread - 8/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[12:15:57] [Craft Scheduler Thread - 8/INFO]: [ChestShopNotifier] Database connected!
```

**Comment by andrewkm** [comment]
Further errors now that users are playing:

```
[12:21:36] [Server thread/INFO]: [ChestShop] XenonGZ bought 10 Iron Ingot for 270.00 from NessXXIII at [rising_n] 7214, 65, 8958
[12:21:37] [Craft Scheduler Thread - 128/WARN]: java.sql.SQLException: No value specified for parameter 9
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2268)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.mysql.jdbc.PreparedStatement.addBatch(PreparedStatement.java:946)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.wfector.lib.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.wfector.notifier.BatchRunner.run(BatchRunner.java:37)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[12:21:37] [Craft Scheduler Thread - 128/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
