### ISSUE TITLE
ERROR Could not pass event TransactionEvent to ChestShopNotifier v1.3.3-SNAPSHOT (build 48)

### ISSUE THREAD

**Issue by MarkHunter1** [ChestShop-authors/ChestShopNotifier#49]
Fresh install of ChestShop 3.11 and ChestShop Notifier Dev Build 48.  Whenever someone buys something the following error is logged and nothing is written to the database.  I'm running Paper Spigot 1.16.5.  Did I miss some dependency?  Please help.  Thanks!!!

30.03 23:25:41 [Server] ERROR Could not pass event TransactionEvent to ChestShopNotifier v1.3.3-SNAPSHOT (build 48)
30.03 23:25:41 [Server] INFO java.lang.NoClassDefFoundError: com/Acrobot/ChestShop/Utils/ItemUtil
30.03 23:25:41 [Server] INFO at com.wfector.notifier.ChestShopNotifier.onChestShopTransaction(ChestShopNotifier.java:245) ~[?:?]
30.03 23:25:41 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor530.execute(Unknown Source) ~[?:?]
30.03 23:25:41 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:153) ~[?:?]
30.03 23:25:41 [Server] INFO at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:529) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-520]
30.03 23:25:41 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Phoenix616** [comment]
You are using an outdated ChestShop version, the latest CSN builds are for the latest ChestShop builds.
