### ISSUE TITLE
1.19.3 error

### ISSUE THREAD

**Issue by x1p** [ChestShop-authors/ChestShopNotifier#65]
I noticed an error on my test server for a while now. I assume chestshopnotifier is not compatible with 1.19.3?
Did I miss anything or made an oopsie?

```
[22:23:42 INFO]: [ChestShopNotifier] Enabling ChestShopNotifier v1.3.4-SNAPSHOT (build 57)
[22:23:42 ERROR]: Error occurred while enabling ChestShopNotifier v1.3.4-SNAPSHOT (build 57) (Is it up to date?)
java.lang.NoClassDefFoundError: com/Acrobot/ChestShop/Events/AccountQueryEvent
at com.wfector.notifier.ChestShopNotifier.onEnable(ChestShopNotifier.java:57) ~[ChestShopNotifier-57.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1875]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1875]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.Acrobot.ChestShop.Events.AccountQueryEvent
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 12 more
[22:23:42 INFO]: [ChestShopNotifier] Disabling ChestShopNotifier v1.3.4-SNAPSHOT (build 57)
[22:23:42 ERROR]: Error occurred while disabling ChestShopNotifier v1.3.4-SNAPSHOT (build 57) (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.wfector.lib.hikari.HikariDataSource.close()" because "this.ds" is null
at com.wfector.notifier.ChestShopNotifier.onDisable(ChestShopNotifier.java:83) ~[ChestShopNotifier-57.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:403) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:587) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:378) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1875]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1875]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1875]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Purpur 1.19.3
ChestShop build 365
ChestShopNotifier build 57

**Comment by Phoenix616** [comment]
Are you sure you are using the latest builds of everything? I'm using them all together just fine. (On Paper though but I kinda doubt that would make any difference)

**Comment by x1p** [comment]
Hmm that's odd.
I double checked with paper and some bare minimum plugins like CMI, WE and WG etc. But the result is the same.

**Comment by x1p** [comment]
Ah I think I found it. I think the database of chestshop was polluted or something. I've reset every trace of old data. Now it seems to load fine.
Thanks.

**Comment by Phoenix616** [comment]
> Ah I think I found it. I think the database of chestshop was polluted or something. I've reset every trace of old data. Now it seems to load fine.

Ok well that sounds a bit strange. That error should only ever be possible if an outdated version of ChestShop was loaded which didn't have that evend class yet. Other configs or data should have no influence on it.
